name: Builds
on:
  push:
    branches:
      - main

jobs:
  windows:
    name: "AutoCompleter-Windows"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller selenium prompt_toolkit
      - name: Verify installed packages
        run: |
          pip list
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile autocompleter.py
      - name: Publish
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: "AutoCompleter-Windows"
          path: dist/autocompleter.exe

  macOS:
    name: "AutoCompleter-macOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller selenium prompt_toolkit
      - name: Verify installed packages
        run: |
          pip list
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile autocompleter.py
      - name: Publish
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: "AutoCompleter-macOS"
          path: dist/autocompleter
